### ISSUE TITLE
Implement MyPosts Section

### ISSUE THREAD

**Issue by Shehanka** [codekittyshow/code-kitty#17]
1. Implement Get Post by userId in the backend and get merge it
2. Use Get post by userId endpoint on the frontend to implement my post section
3. Users should be able to delete/edit their existing posts.

`API = api/v1/post/user/:UserID`

**Comment by khan9920** [comment]
The FE throws an error since there is no `user` object in the API response. @Safnaj @Shehanka please fix this and confirm.

**API RESPONSE**

![image](https://user-images.githubusercontent.com/29376547/145680671-5d52443e-200a-4b39-aa34-0b2c24f891b5.png)

**FE ERROR**

![image](https://user-images.githubusercontent.com/29376547/145680762-4d240e2f-c0ab-4581-aeda-9bf3c58f547d.png)

![image](https://user-images.githubusercontent.com/29376547/145680770-1dacdd96-930b-49df-a757-27a1c8681db7.png)
